'use strict'; /*jslint node:true es9:true*/

// Lint config pinned to the style this repo already had, not to a style a
// popular preset prefers.
//
// There is deliberately no Prettier here. This codebase puts the brace of a
// multi-line block on its own line but keeps it on the same line for function
// declarations, and omits spaces around binary operators — a combination
// Prettier cannot express and would silently rewrite. Running it would
// reformat every line of every file, and then every future contributor's diff
// would be indistinguishable from that reformat. The rules below encode the
// conventions that actually matter (correctness, unused code, equality) and
// leave the author's formatting alone.

import js from '@eslint/js';

export default [
    {
        ignores: [
            'node_modules/**',
            'build/**',
            'dist/**',
            // Generated by scripts/build.mjs — 744 KB of somebody else's code.
            '2captcha-mcp.mjs',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                fetch: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                URL: 'readonly',
                Buffer: 'readonly',
                TextEncoder: 'readonly',
                globalThis: 'readonly',
                AbortController: 'readonly',
            },
        },
        rules: {
            // `catch(_e){ /* already dead */ }` is a deliberate idiom here:
            // the binding is required by older syntax targets even when the
            // error is genuinely uninteresting.
            'no-unused-vars': ['error', {
                argsIgnorePattern: '^_',
                caughtErrorsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
            }],
            eqeqeq: ['error', 'always'],
            'no-var': 'error',
            'prefer-const': 'error',
            'no-throw-literal': 'error',
            'no-return-await': 'off',
            'no-console': 'off',
            // Every diagnostic this server prints goes to stderr, because
            // stdout IS the MCP transport. A stray console.log corrupts the
            // protocol stream, which is why this one is an error and not a
            // style preference.
            'no-restricted-properties': ['error', {
                object: 'console',
                property: 'log',
                message: 'stdout is the MCP transport — use console.error, '
                    +'or the log() helper, so diagnostics go to stderr.',
            }],
            // ignoreComments because this codebase aligns a wrapped trailing
            // comment under the one above it, which is more readable than the
            // statement indent the rule would otherwise demand.
            indent: ['error', 4, {SwitchCase: 1, flatTernaryExpressions: true,
                ignoreComments: true}],
            semi: ['error', 'always'],
            quotes: ['error', 'single',
                {avoidEscape: true, allowTemplateLiterals: true}],
            'comma-dangle': 'off',
            'no-multiple-empty-lines': ['error', {max: 1}],
            'eol-last': ['error', 'always'],
        },
    },
    {
        // Build and release scripts are CLIs: their whole output contract is
        // stdout, and they never speak MCP.
        files: ['scripts/**', 'examples/**', 'connect-check.mjs'],
        rules: {'no-restricted-properties': 'off'},
    },
    {
        files: ['test/**'],
        languageOptions: {
            globals: {console: 'readonly', process: 'readonly',
                setTimeout: 'readonly', clearTimeout: 'readonly',
                URL: 'readonly', Buffer: 'readonly', fetch: 'readonly'},
        },
        rules: {'no-restricted-properties': 'off'},
    },
];
